export const categoryItems = [
    { id: "1", text: "NFTS" },
    { id: "2", text: "NEUROSCIENCE" },
    { id: "3", text: "PEER REVIEW" },
    { id: "4", text: "DENTIST" },
    { id: "5", text: "IDENTITY" },
    { id: "6", text: "REPUTATION" },
    { id: "7", text: "AI" },
    { id: "8", text: "PUBLISHING" },
    { id: "9", text: "BIOBANKING" },
    { id: "10", text: "BIOHACKING" },
    { id: "11", text: "BLOCKCHAIN PROTOCOL" },
    { id: "12", text: "COMMUNITY" },
    { id: "13", text: "SPACE" },
    { id: "14", text: "COMPUTE" },
    { id: "15", text: "DAO" },
    { id: "16", text: "LONGEVITY" },
    { id: "17", text: "DATA" },
    { id: "18", text: "PHARMA" },
    { id: "19", text: "DECENTRALISED TRIALS" },
    { id: "20", text: "INCUBATOR" },
    { id: "21", text: "ECOSYSTEM" },
    { id: "22", text: "FOCUSED RESEARCH" },
    { id: "23", text: "STORAGE" },
    { id: "24", text: "FUNDING" },
    { id: "25", text: "GENOMICS" },
    { id: "26", text: "SCIENCE DEFI" },
    { id: "27", text: "HEALTHCARE" },
    { id: "28", text: "PHILANTHROPY" },
    { id: "29", text: "CLIMATE" },
    { id: "30", text: "ANTHROPOLOGY" },
    { id: "31", text: "BOTANY" }
];